apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    tier: frontend
spec:
  containers:
  - image: marprz94/my-calculator-app:latest
    name: nodewebapp
    ports:
    - containerPort: 3000
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  